"""indexing dateTime

Revision ID: 39a9db1ad708
Revises: 9ec8ec60b26d
Create Date: 2020-03-19 22:15:40.673488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a9db1ad708'
down_revision = '9ec8ec60b26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reading_datetime'), 'reading', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_datetime'), table_name='reading')
    # ### end Alembic commands ###
